# Generated by Django 6.0.5 on 2026-06-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Accounts/admin'), ('SALES', 'Sales Attendant'), ('MANAGER', 'Store Manager'), ('CASHIER', 'Cashier')], default='SALES', max_length=10),
        ),
    ]
