# Generated by Django 6.0.5 on 2026-06-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemedeposit',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='schemes.savingsscheme'),
        ),
        migrations.AlterField(
            model_name='schemewithdrawal',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='schemes.savingsscheme'),
        ),
    ]
