# Generated by Django 6.0.5 on 2026-06-03 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_alter_schemedeposit_scheme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schemedeposit',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schemedeposit',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Cash Deposit (+)'), ('RELEASE', 'Goods Released (-)')], default='DEPOSIT', max_length=10),
        ),
    ]
